### ISSUE TITLE
Distinguish "owned" specifications in the list

### ISSUE THREAD

**Issue by alexkaserbacher** [TNG/ApiCenter#30]
Distinguish on specification overview between "general" specifications and specifications created by the logged in user. First of all, there needs to be an association on the data model and within the backend domain. There are some possibilities on how to distinguish your own and other specifications in the frontend:
- Show your own specifications on top of the specification list
- Somehow visually tag your own specification
- Provide two seperate lists of specifications (e.g. "All Specifications" & "Your Specifications") where you can switch between both of them via tabs

**Comment by fdw** [comment]
I think this very closely related to #5: It should be possible to associate a specification with more than one user (i.e. the responsible developers), and it should be possible to have different rights for these users. Maybe we need a relation `specification`-`user`-`permission level`? This would also allow for users to have unusually few permissions.

Or should this "author" association be totally separate from permission management? However, this will probably confuse users.

**Comment by alexkaserbacher** [comment]
Correct. Although, I see this as kind of a "precondition" for permission-management. This issue has solely the purpose of associating users with specifications and generating views for that such that the user can somehow distinguish between "his own" specifications and others.

Permission management would then be an addition to that, such that you can specify what others can see/edit about your specifications.

I thought it would be better to split this into two separate issues.

**Comment by fdw** [comment]
I'm not sure if separating both issues isn't more work, that's why I commented yesterday: If I understand this issue correctly, each spec has exactly one "author" who can then (with #5) change its permissions. 
However, I don't think that one author is the best idea - a spec is usually developed by a team, which must be stored and managed differently. Therefore I think it might make sense to include permission management at least in the design, so that we don't need to rework everything.

In essence, I think we want an ACL for the specs, so I'd say we use that already for this ticket even if we don't need its full might.

**Comment by alexkaserbacher** [comment]
I agree on the implementation details (i.e. instantiating a many-to-many instead of a one-to-many between specifications and users). Interesting question: should we introduce permission-management on versions too? Or is the granularity of specification-permissions already enough!?

Regarding the splitting of the issues: this issue has one focus that does not directly come to mind when thinking about permission management - as I mentioned before, the focus is to visually seperate your "owned" specifications (i.e. later on also specifications that you have write acces to) from all the other specifications, as I may want to quickly see all my owned specifications as a developer (since I'm obligated to maintain them, and/or delete them).

**Comment by fdw** [comment]
Please bear for a moment with my pipe dream here: I don't want too many configuration options, because that makes everything complicated without achieving a lot. So, I don't think permissions per version are sensible (why should somebody maintain one version, but not another). However (sorry ;)), separating permissions between stable and proposed (SNAPSHOT) versions makes sense again: Most developers can see the stable spec, but you want to show the new proposal to a handful of people so you can discuss it. So this is what I would like to see.

Regarding this issue: I'm sorry, I've understood it to mean way more than just a visual distinction (i.e. associating authors to a spec). Just separating them in the list (maybe with color (think about colorblind people), maybe with a filter) is a good idea. I just wanted to prevent a data structure that will be obsolete as soon as we start on the permission system. I'll go ahead and change the title so we both know what is meant.
